# Generated by Django 5.1 on 2024-10-21 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='AssignSection',
            new_name='AssignSection_id',
        ),
        migrations.AddField(
            model_name='staffs',
            name='max_load',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GradeLevel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.gradelevel'),
        ),
        migrations.CreateModel(
            name='StudentPromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(default=django.utils.timezone.now)),
                ('new_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_grade', to='student_management_app.gradelevel')),
                ('previous_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_grade', to='student_management_app.gradelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
            ],
        ),
    ]
