# Generated by Django 5.1 on 2024-10-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancepayment',
            old_name='remarks',
            new_name='payment_balance_remarks',
        ),
    ]
