# Generated by Django 5.1 on 2024-11-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='balancepayment',
            name='remarks',
        ),
        migrations.AddField(
            model_name='balancepayment',
            name='payment_balance_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_soft_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
