# Generated by Django 5.1 on 2024-08-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_attendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_grading_active', models.BooleanField(default=True)),
            ],
        ),
    ]
