# Generated by Django 5.1 on 2024-09-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_staffs_age_staffs_tin_id_students_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='enrolling_teacher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='referred_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='telephone_nos',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='father_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='guardian_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='guardian_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='mother_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='mother_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='previousschool',
            name='grade_level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='previousschool',
            name='school_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='previousschool',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='previousschool',
            name='school_year_attended',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='previousschool',
            name='teacher_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='age',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='blood_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='cellphone_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='dual_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='gsis_id',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='pagibig_id',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='philhealth_id',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='sss_id',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='telephone_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='tin_id',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Enrollment_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_vaccination',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade_level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile_phone_nos',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='place_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='rank_in_family',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='religion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_number',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='suffix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='telephone_nos',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_eight',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_five',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_four',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_nine',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_one',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_seven',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_six',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_ten',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_three',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
