# Generated by Django 5.1 on 2024-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_schedule_classroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
