# Generated by Django 5.1 on 2024-09-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_emergencycontact_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='grade_level',
        ),
    ]
