# Generated by Django 5.1 on 2024-11-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_customuser_last_login_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_session_key',
        ),
    ]
