# Generated by Django 5.1 on 2024-09-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_remove_students_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_number',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
