# Generated by Django 5.1 on 2024-09-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_remove_students_grade_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='address',
            new_name='emergency_contact_address',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='name',
            new_name='emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='telephone_nos',
            new_name='emergency_contact_phone',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='relation',
            new_name='emergency_contact_relationship',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='date',
            new_name='emergency_date',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='enrolling_teacher',
            new_name='emergency_enrolling_teacher',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='referred_by',
            new_name='emergency_referred_by',
        ),
        migrations.RenameField(
            model_name='previousschool',
            old_name='grade_level',
            new_name='previous_grade_level',
        ),
        migrations.RenameField(
            model_name='previousschool',
            old_name='school_address',
            new_name='previous_school_address',
        ),
        migrations.RenameField(
            model_name='previousschool',
            old_name='school_name',
            new_name='previous_school_name',
        ),
        migrations.RenameField(
            model_name='previousschool',
            old_name='teacher_name',
            new_name='previous_teacher_name',
        ),
        migrations.RemoveField(
            model_name='previousschool',
            name='school_year_attended',
        ),
        migrations.AddField(
            model_name='previousschool',
            name='previous_school_year_attended',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
