# Generated by Django 5.1 on 2024-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_alter_students_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_number',
            field=models.CharField(blank=True, editable=False, max_length=9, null=True, unique=True),
        ),
    ]
