# Generated by Django 5.1 on 2024-12-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Taken', 'Taken')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_ID_number', models.CharField(blank=True, max_length=255, null=True)),
                ('school_district', models.CharField(blank=True, max_length=255, null=True)),
                ('school_division', models.CharField(blank=True, max_length=255, null=True)),
                ('school_region', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='balancepayment',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='session_year_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='balancepayment',
            name='payment_balance_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='staff_employment_info',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff_physical_info',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_physical_info',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='citizenship',
            field=models.CharField(blank=True, default='Filipino', max_length=20, null=True),
        ),
    ]
