# Generated by Django 5.1 on 2024-09-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='age',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
