# Generated by Django 5.1 on 2024-09-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
