# Generated by Django 5.1 on 2024-11-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_classroom_remove_balancepayment_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='classroom_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.classroom'),
            preserve_default=False,
        ),
    ]
