# Generated by Django 5.1 on 2024-11-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_students_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_soft_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
