# Generated by Django 5.1 on 2024-12-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='status',
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
