# Generated by Django 5.1 on 2024-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_classroom_school_info_remove_balancepayment_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
