# Generated by Django 5.1 on 2024-09-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_students_gradelevel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='AssignSection',
            new_name='AssignSection_id',
        ),
    ]
