# Generated by Django 5.1 on 2024-09-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_staffs_tin_id_alter_staffs_gsis_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Enrollment_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
