# Generated by Django 5.1 on 2024-11-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_staff_physical_info_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='session_year_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='staff_id',
        ),
    ]
