# Generated by Django 5.1 on 2024-11-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_customuser_failed_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_employment_info',
            name='max_load',
        ),
        migrations.AddField(
            model_name='adminhod',
            name='max_load',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='max_load',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
