# Generated by Django 5.1 on 2024-11-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_remove_schedule_session_year_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='classroom_id',
        ),
    ]
