# Generated by Django 5.1 on 2024-12-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_remove_staff_employment_info_max_load_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_assignment_marks',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_exam_marks',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
