# Generated by Django 5.1 on 2024-12-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_remove_schedule_classroom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_ID_number', models.CharField(blank=True, max_length=255, null=True)),
                ('school_district', models.CharField(blank=True, max_length=255, null=True)),
                ('school_division', models.CharField(blank=True, max_length=255, null=True)),
                ('school_region', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentresult',
            name='general_average',
            field=models.FloatField(default=0),
        ),
    ]
