# Generated by Django 5.1 on 2024-11-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_school_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='general_average',
            field=models.FloatField(default=0),
        ),
    ]
