# Generated by Django 5.1 on 2024-12-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_remove_studentresult_subject_assignment_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_contact_info',
            old_name='emergency_contact',
            new_name='emergency_contact_name',
        ),
        migrations.AddField(
            model_name='staff_contact_info',
            name='emergency_contact_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
