# Generated by Django 5.1 on 2024-12-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_school_info_studentresult_general_average'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School_info',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='general_average',
        ),
    ]
