# Generated by Django 5.1 on 2024-12-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_rename_emergency_contact_staff_contact_info_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_contact_info',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff_contact_info',
            name='emergency_contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
