# Generated by Django 5.1 on 2024-12-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_delete_school_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Taken', 'Taken')], max_length=10, null=True),
        ),
    ]
